name: Build samples

on:
  pull_request:
  push:
  schedule:
    # Run at 03:00 UTC on every Sunday
    - cron: '0 3 * * 0'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ncs-playground

      - name: Get the version
        id: get_version
        working-directory: ncs-playground
        run: echo "VERSION=$(git describe --always --tags)" >> $GITHUB_OUTPUT

      - name: Initialize
        working-directory: ncs-playground
        run: |
          west init -l .
          west update

      - name: Build samples
        working-directory: ncs-playground
        run: |
          west twister --integration -v --inline-logs -T samples

      - name: Tar firmware
        working-directory: ncs-playground/twister-out
        run: |
          find . \( -name zephyr.uf2 -or -name zephyr.hex \) -print0 | tar -cvf ncs-playground-samples-${{ steps.get_version.outputs.VERSION }}.tar --null -T -

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: ncs-playground-samples-${{ steps.get_version.outputs.VERSION }}
          path: |
            ncs-playground/twister-out/ncs-playground-samples-${{ steps.get_version.outputs.VERSION }}.tar

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: |
            ncs-playground/twister-out/ncs-playground-samples-${{ steps.get_version.outputs.VERSION }}.tar